#!/usr/bin/env python3
"""
环境变量配置 setup 脚本

功能：
1. 检测已实现的引擎
2. 让用户选择引擎
3. 收集该引擎需要的环境变量
4. 生成 .env 文件
"""
import sys
import os
from pathlib import Path
from typing import Dict, List, Any


def detect_engines() -> List[str]:
    """检测已实现的引擎"""
    engines_dir = Path(__file__).parent / "engines"
    available = []

    # 查找所有引擎实现
    for file in engines_dir.glob("*.py"):
        if file.stem not in ['__init__', 'base', 'models']:
            available.append(file.stem)

    return available


def load_engine_class(engine_name: str):
    """动态加载引擎类"""
    import importlib

    module_name = f"engines.{engine_name}"
    try:
        module = importlib.import_module(module_name)
        # 假设类名是 <EngineName>Engine，如 MulticaEngine, GithubEngine
        class_name = f"{engine_name.capitalize()}Engine"
        return getattr(module, class_name)
    except (ImportError, AttributeError) as e:
        print(f"❌ 无法加载引擎 {engine_name}: {e}")
        return None


def prompt_choice(question: str, choices: List[str]) -> str:
    """让用户从列表中选择"""
    print(f"\n{question}")
    for i, choice in enumerate(choices, 1):
        print(f"  {i}. {choice}")

    while True:
        try:
            answer = input("\n请输入选项编号: ").strip()
            idx = int(answer) - 1
            if 0 <= idx < len(choices):
                return choices[idx]
            print(f"❌ 请输入 1-{len(choices)} 之间的数字")
        except (ValueError, KeyboardInterrupt):
            print("\n❌ 已取消")
            sys.exit(1)


def prompt_input(prompt_text: str, default: str = None, validator=None, optional: bool = False) -> str:
    """让用户输入值。optional=True 时允许留空（返回 ""）。"""
    if default:
        full_prompt = f"{prompt_text} [{default}]: "
    else:
        full_prompt = f"{prompt_text}: "

    while True:
        try:
            value = input(full_prompt).strip()
            if not value and default:
                value = default

            if not value:
                if optional:
                    return ""
                print("❌ 不能为空，请重新输入")
                continue

            # 运行验证器
            if validator and not validator(value):
                print("❌ 输入不合法，请重新输入")
                continue

            return value
        except KeyboardInterrupt:
            print("\n❌ 已取消")
            sys.exit(1)


def collect_env_vars(engine_class) -> Dict[str, str]:
    """收集引擎需要的环境变量"""
    env_vars = {}

    # 1. 收集通用环境变量
    print("\n" + "="*60)
    print("📋 配置通用环境变量")
    print("="*60)

    common_vars = engine_class.get_common_env_vars()
    for var_spec in common_vars:
        name = var_spec['name']
        description = var_spec.get('description', '')

        if 'choices' in var_spec:
            # 选择题
            value = prompt_choice(
                f"{description} ({name})",
                var_spec['choices']
            )
        else:
            # 输入题
            value = prompt_input(
                var_spec.get('prompt', f"请输入 {name}"),
                default=var_spec.get('default'),
                validator=var_spec.get('validator')
            )

        env_vars[name] = value

    # 2. 收集引擎特定环境变量
    print("\n" + "="*60)
    print(f"📋 配置 {env_vars.get('ENGINE_TYPE', '引擎')} 特定环境变量")
    print("="*60)

    engine_vars = engine_class.get_required_env_vars()
    for var_spec in engine_vars:
        name = var_spec['name']
        description = var_spec.get('description', '')

        if 'choices' in var_spec:
            value = prompt_choice(
                f"{description} ({name})",
                var_spec['choices']
            )
        else:
            value = prompt_input(
                var_spec.get('prompt', f"请输入 {name}"),
                default=var_spec.get('default'),
                validator=var_spec.get('validator'),
                optional=var_spec.get('optional', False)
            )

        # 可选项留空 → 不写入 .env，保持配置文件干净
        if value == "" and var_spec.get('optional'):
            continue
        env_vars[name] = value

    return env_vars


def save_env_file(env_vars: Dict[str, str], env_path: Path):
    """保存 .env 文件"""
    lines = [
        "# DAG Orchestration Engine Configuration",
        f"# Generated by setup.py",
        "",
    ]

    # 按 ENGINE_TYPE 开头，其他按字母排序
    sorted_keys = sorted(env_vars.keys(), key=lambda k: (k != 'ENGINE_TYPE', k))

    for key in sorted_keys:
        value = env_vars[key]
        # 如果值包含空格或特殊字符，加引号
        if ' ' in value or '#' in value:
            value = f'"{value}"'
        lines.append(f"{key}={value}")

    content = "\n".join(lines) + "\n"
    env_path.write_text(content)
    print(f"\n✅ 配置已保存到 {env_path}")


def list_existing_workspaces(engine_class):
    """列出已有的工作空间（如果引擎支持）"""
    try:
        # 这里可以调用引擎的 CLI 列出工作空间
        # 例如：multica workspace list
        # 但需要引擎提供这个能力
        if hasattr(engine_class, 'list_workspaces'):
            return engine_class.list_workspaces()
    except:
        pass
    return None


def main():
    print("="*60)
    print("🚀 DAG Orchestration Engine Setup")
    print("="*60)

    # 确定 .env 文件位置（skill 根目录）
    skill_root = Path(__file__).parent.parent
    env_path = skill_root / ".env"

    # 检查是否已有 .env
    if env_path.exists():
        print(f"\n⚠️  发现已有配置文件: {env_path}")
        overwrite = input("是否覆盖？(y/N): ").strip().lower()
        if overwrite != 'y':
            print("❌ 已取消")
            return

    # 1. 检测可用引擎
    available_engines = detect_engines()
    if not available_engines:
        print("❌ 未找到任何引擎实现！")
        sys.exit(1)

    print(f"\n✅ 检测到 {len(available_engines)} 个可用引擎:")
    for engine in available_engines:
        print(f"  - {engine}")

    # 2. 让用户选择引擎
    engine_name = prompt_choice(
        "🎯 请选择要使用的引擎:",
        available_engines
    )

    # 3. 加载引擎类
    engine_class = load_engine_class(engine_name)
    if not engine_class:
        sys.exit(1)

    # 4. 收集环境变量
    env_vars = collect_env_vars(engine_class)

    # 5. 保存 .env
    save_env_file(env_vars, env_path)

    # 6. 显示摘要
    print("\n" + "="*60)
    print("📊 配置摘要")
    print("="*60)
    for key, value in env_vars.items():
        # 隐藏敏感信息（如果有 token/key/secret 关键字）
        if any(keyword in key.lower() for keyword in ['token', 'key', 'secret', 'password']):
            display_value = "***"
        else:
            display_value = value
        print(f"  {key} = {display_value}")

    print("\n✅ Setup 完成！现在可以运行:")
    print(f"    cd {skill_root}")
    print(f"    python3 scripts/run_dag.py manifest.yaml")


if __name__ == '__main__':
    main()
